const ICON_SIZES: Record<string, number> = {
  uva: 30,
  tangerina: 30,
  pessego: 30,
  pera: 35,
  noz_fruto_seco: 22,
  melao: 30,
  melancia: 30,
  marmelo: 22,
  maracuja: 26,
  manga: 30,
  mamao: 35,
  maca: 30,
  limao: 25,
  laranja: 30,
  goiaba: 30,
  figo: 35,
  caqui: 22,
  caju: 33,
  banana_cacho: 30,
  acai: 30,
  abacaxi: 35,
  abacate: 33,
  algodao_arboreo_em_caroco : 30,
  algodao_herbaceo_em_caroco : 30,
  amendoim_em_casca: 30,
  aveia_em_grao: 23,
  centeio_em_grao: 23,
  cevada_em_grao: 23,
  ervilha_em_grao: 35,
  fava_em_grao: 30,
  feijao_em_grao: 28,
  girassol_em_grao: 35,
  linho_semente: 35,
  milho_em_grao: 40,
  soja_em_grao: 30,
  sorgo_em_grao: 38,
  trigo_em_grao: 35,
  triticale_em_grao: 30,
};

export default ICON_SIZES;

